### ISSUE TITLE
Cannot filter the users

### ISSUE THREAD

**Issue by stevethomas19** [BYU-ODH/hummedia-client#34]
When typing into the users box, the results are not being filtered.

**Comment by krisalder** [comment]
I can't reproduce this bug in my dev environment, although I've verified that it is happening in production.

My first guess was that it was a performance issue because of the much larger number of users in the production database, but everything still worked as expected after adding 20k users to my dev environment.

**Comment by webnard** [comment]
Are you able to retrieve any users at all on the production site? I think
the server is just mega laggy. I'm not seeing any show up at all.

On Thu, Apr 28, 2016 at 12:08 PM, krisalder <notifications@github.com>
wrote:

> I can't reproduce this bug in my dev environment, although I've verified
> that it is happening in production.
>
> My first guess was that it was a performance issue because of the much
> larger number of users in the production database, but everything still
> worked as expected after adding 20k users to my dev environment.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ODH/hummedia-client/issues/34#issuecomment-215479620>
>



-- 
 ian hunter

**Comment by krisalder** [comment]
I think I figured it out. At least one (and possible more) users in the production database have null or undefined first/last/full names. This causes a JavaScript error when the toLowerCase() function is called. I've got a fix and will submit a pull request momentarilly.
